### ISSUE TITLE
shits fucked lol

### ISSUE THREAD

**Issue by LordOfErebus** [Madobe/giveaway_bot#1]
duplicate item ddetection thing (eg. things with "x6" isn't being put into separate rows anymore) is fucked, "N/A" is being put into the sheet, (it should just be blank) and i think we had auto-capitalization of things which isn't working anymore either. Probably some other stuff i havent noticed too

**Comment by Madobe** [comment]
- Amount parsing is back.
- "N/A" is no longer put in the Donor Notes column when "N" is the provided input.
- Auto-capitalization is back.
